### ISSUE TITLE
Output might produce scientific notation

### ISSUE THREAD

**Issue by rileyjshaw** [avwuff/SVG-to-GCode#4]
Right now, the app can output instructions like:

`G1 X3.56065 Y8E-05`

…which is interpreted as an `E` instruction. It causes the cutter software to throw an error.

I can't easily test this, but I think we can fix it by using `Format()` instead of `Round()` in [SVGParse.bas](https://github.com/avwuff/SVG-to-GCode/blob/master/src/SVGParse.bas).

**Comment by avwuff** [comment]
I'm curious -- where are you experiencing this bug?  Could you send me the SVG file?  I've tried to get Round to do that and it just won't -- it just puts out 0.0005 or 0.

**Comment by rileyjshaw** [comment]
Sure thing! Example SVG: http://s000.tinyupload.com/index.php?file_id=00061992575784275888

`System info:`
`MacOS Sierra 10.12.5 (16F73)`
`SVG to GCODE v1.2.3`

**Comment by avwuff** [comment]
Hmm I bet you the problem you are experiencing is a shitty implementation of Round() in the Wine library… because the PC version doesn’t do that :(

There was a similar problem I had to fix before the Wine code would even work…  
It’s hard to fix bugs in code that is only doing it in systems you don’t control :-)

In any case, I have replaced Round() with Format() and updated the git and the installer.  Unfortunately I don’t have the tools to create a new WineBottler installer…


Thanks!
-alex

**Comment by rileyjshaw** [comment]
> Unfortunately I don’t have the tools to create a new WineBottler installer…'

Ah, but I do! 😄 I just spent a while trying to get this bundled but it's my first time using WineBottler; the output won't run. Any tips @f3ndot? It'd be good for us to add WineBottler config settings to the README for future noobs like me.
