### ISSUE TITLE
Automatic export when source file changes

### ISSUE THREAD

**Issue by amirm** [avwuff/SVG-to-GCode#6]
Hello.

There are many small things to improve in this wonderful program...
- Output in G21 (mm)
- Use . as decimal separator instead of ,
- offset output so that lowest left corner is at 0,0
- set default S value
- stop putting "M62 P0" - bCNC does not like it..

So I made a C# program that reads SVG-to-GCode generated file and corrects all these little things, so I would no bother you!

However, there is one thing I can´t do it with my program...

A checkbox that enables "Automatic Convert"
My C# program has one! Here´s how it works:

When the checkbox is checked, my C# program will 
- read the source file´s "last written date"
- start a 1second timer

When the checkbox is unchecked, my C# program will stop the timer.

At the timer function, it reads the source file´s "last written date" and compares.
If the file has changed, it rebuilds.

This helps to make a workflow:
When I save a file in Inkscape...
SVG-to-GCode will notice file has changed and automatically reconvert.
My C# program will notice file has changed, "fix" it, and save to another file.
bCNC will notice file has changed and prompt to read again (it does!)

A few last words:
I did a timer because I´m lazy. I should use a notification... shame on me!

In the Export dialog (where there is the "Export Now" button) there could be an option of Rotation (0, 90, 180, 270) so that rotation will also be done automatically, and not because user pressed the "Rotate 90" button.

It would also be nice to have Xmirror and Ymirror..

Thank you

**Comment by avwuff** [comment]
Hi, and thanks for your interest!

I don't want to add an 'automatic export when source file changes' because it would lose any changes you made in SVG to GCode, such as scaling, tiling, removing sections, etc.

I also don't really use this application anymore and currently don't have the time to maintain it - feel free to make the changes needed! 

At some point I may convert this to a C# application, but that is a lot of work.

Cheers!
